name: CI

# Workflow runs on push to master and pull requests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test

  build:
    runs-on: ubuntu-latest
    name: Build Extension
    needs: test
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Generate icons
      run: npm run generate-icons
      
    - name: Create extension package
      run: |
        zip -r extension.zip . \
          -x "node_modules/*" \
          -x ".git/*" \
          -x ".github/*" \
          -x "*.zip" \
          -x "__tests__/*" \
          -x "jest.config.js" \
          -x "jest.e2e.config.js" \
          -x "jest.e2e.setup.js"
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: extension-package
        path: extension.zip 